Repository MeshManager/MeshManagerBack, pull requests merged in 2025-06, with the labels that each got.

#1 agent와 통신하는 API 구현
  .gitattributes
  .gitignore
  agent-service/build.gradle
  agent-service/gradle/wrapper/gradle-wrapper.jar
  agent-service/gradle/wrapper/gradle-wrapper.properties
  agent-service/gradlew
  agent-service/gradlew.bat
  agent-service/settings.gradle
  agent-service/src/main/java/org/agent/service/AgentApplication.java
  agent-service/src/main/java/org/agent/service/api/AgentController.java
  agent-service/src/main/java/org/agent/service/common/StatusResponse.java
  agent-service/src/main/java/org/agent/service/config/RedisConfig.java
  agent-service/src/main/java/org/agent/service/config/SwaggerConfig.java
  agent-service/src/main/java/org/agent/service/dto/RegisterAgentRequest.java
  agent-service/src/main/java/org/agent/service/dto/SaveClusterStateRequest.java
  agent-service/src/main/java/org/agent/service/entity/Agent.java
  agent-service/src/main/java/org/agent/service/exception/GlobalExceptionHandler.java
  agent-service/src/main/java/org/agent/service/repository/AgentRepository.java
  agent-service/src/main/java/org/agent/service/service/AgentService.java
  agent-service/src/main/java/org/agent/service/service/RedisService.java
  agent-service/src/main/resources/application-dev.yaml
Labels: enhancement

#2 agent 등록하는 API 수정
  agent-service/src/main/java/org/agent/service/dto/RegisterAgentRequest.java
  agent-service/src/main/java/org/agent/service/entity/Agent.java
  agent-service/src/main/java/org/agent/service/service/AgentService.java
Labels: bug

#4 클러스터 리소스 조회 API 구현
  cluster-management-service/src/main/java/org/management/service/api/ManagementController.java
  cluster-management-service/src/main/java/org/management/service/dto/request/ClusterResourceRequest.java
  cluster-management-service/src/main/java/org/management/service/dto/request/Resource.java
  cluster-management-service/src/main/java/org/management/service/dto/response/ClusterNamespacesResponse.java
  cluster-management-service/src/main/java/org/management/service/dto/response/ClusterServicesResponse.java
  cluster-management-service/src/main/java/org/management/service/repository/ClusterResourceRepository.java
  cluster-management-service/src/main/java/org/management/service/service/ManagementService.java
Labels: enhancement

#5 클러스터의 deployment 목록 조회 API 구현
  cluster-management-service/src/main/java/org/management/service/api/ManagementController.java
  cluster-management-service/src/main/java/org/management/service/common/DataResponse.java
  cluster-management-service/src/main/java/org/management/service/dto/ContainerInfo.java
  cluster-management-service/src/main/java/org/management/service/dto/response/DeploymentResponse.java
  cluster-management-service/src/main/java/org/management/service/repository/ClusterResourceRepository.java
  cluster-management-service/src/main/java/org/management/service/service/ManagementService.java
Labels: enhancement

#6 클러스터 서비스 API 구현
  cluster-service/build.gradle
  cluster-service/gradle/wrapper/gradle-wrapper.jar
  cluster-service/gradle/wrapper/gradle-wrapper.properties
  cluster-service/gradlew
  cluster-service/gradlew.bat
  cluster-service/settings.gradle
  cluster-service/src/main/java/org/istizo/clusterservice/ClusterApplication.java
  cluster-service/src/main/java/org/istizo/clusterservice/api/ClusterController.java
  cluster-service/src/main/java/org/istizo/clusterservice/common/DataResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/common/StatusResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/config/RestTemplateConfig.java
  cluster-service/src/main/java/org/istizo/clusterservice/config/SwaggerConfig.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/ContainerInfo.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/DeploymentInfo.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/request/RegisterClusterRequest.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/ClusterListResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/DeploymentListResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/NamespaceListResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/RegisterClusterResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/ServiceNameListResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/entity/Cluster.java
  cluster-service/src/main/java/org/istizo/clusterservice/exception/GlobalExceptionHandler.java
  cluster-service/src/main/java/org/istizo/clusterservice/repository/ClusterRepository.java
  cluster-service/src/main/java/org/istizo/clusterservice/service/ClusterService.java
  cluster-service/src/main/resources/application-dev.yaml
Labels: enhancement

#7 클러스터의 CRD 조회 API 구현
  cluster-management-service/src/main/java/org/management/service/api/ManagementController.java
  cluster-management-service/src/main/java/org/management/service/entity/ClusterCRD.java
  cluster-management-service/src/main/java/org/management/service/repository/ClusterCRDRepository.java
  cluster-management-service/src/main/java/org/management/service/service/ManagementService.java
Labels: enhancement

#8 클러스터 서비스의 API 설명 작성
  cluster-service/src/main/java/org/istizo/clusterservice/api/ClusterController.java
Labels: documentation

#10 에이전트 서비스의 API 설명 작성
  agent-service/src/main/java/org/agent/service/api/AgentController.java
Labels: documentation

#11 불필요한 API 제거
  cluster-management-service/src/main/java/org/management/service/api/ManagementController.java
  cluster-management-service/src/main/java/org/management/service/entity/ClusterCRD.java
  cluster-management-service/src/main/java/org/management/service/repository/ClusterCRDRepository.java
  cluster-management-service/src/main/java/org/management/service/service/ManagementService.java
Labels: invalid

#12 Vsxd 66 backend 배포 관련 api 제작
  crd-service/.gitattributes
  crd-service/.gitignore
  crd-service/build.gradle
  crd-service/gradle/wrapper/gradle-wrapper.jar
  crd-service/gradle/wrapper/gradle-wrapper.properties
  crd-service/gradlew
  crd-service/gradlew.bat
  crd-service/settings.gradle
  crd-service/src/main/java/com/istizo/crd_service/CrdServiceApplication.java
  crd-service/src/main/java/com/istizo/crd_service/domain/DarknessRelease.java
  crd-service/src/main/java/com/istizo/crd_service/domain/Dependency.java
  crd-service/src/main/java/com/istizo/crd_service/domain/IstioRoute.java
  crd-service/src/main/java/com/istizo/crd_service/domain/ServiceEntity.java
  crd-service/src/main/java/com/istizo/crd_service/domain/enums/ServiceType.java
  crd-service/src/main/java/com/istizo/crd_service/global/config/SwaggerConfig.java
  crd-service/src/main/java/com/istizo/crd_service/global/config/webConfig/WebMvcConfig.java
  crd-service/src/main/java/com/istizo/crd_service/global/exception/CustomException.java
  crd-service/src/main/java/com/istizo/crd_service/global/exception/GlobalExceptionHandler.java
  crd-service/src/main/java/com/istizo/crd_service/global/response/ErrorDTO.java
  crd-service/src/main/java/com/istizo/crd_service/global/response/ResForm.java
  crd-service/src/main/java/com/istizo/crd_service/global/response/ResponseDTO.java
  crd-service/src/main/java/com/istizo/crd_service/global/response/status/ErrorStatus.java
  crd-service/src/main/java/com/istizo/crd_service/global/response/status/InSuccess.java
  crd-service/src/main/java/com/istizo/crd_service/repository/DarknessReleaseRepository.java
  crd-service/src/main/java/com/istizo/crd_service/repository/DependencyRepository.java
  crd-service/src/main/java/com/istizo/crd_service/repository/ServiceEntityRepository.java
  crd-service/src/main/java/com/istizo/crd_service/service/CrdService/CrdService.java
  crd-service/src/main/java/com/istizo/crd_service/service/CrdService/CrdServiceImpl.java
  crd-service/src/main/java/com/istizo/crd_service/service/IstioRouteService/IstioRouteService.java
  crd-service/src/main/java/com/istizo/crd_service/service/IstioRouteService/IstioRouteServiceImpl.java
  crd-service/src/main/java/com/istizo/crd_service/web/api/CrdApiSpecification.java
  crd-service/src/main/java/com/istizo/crd_service/web/controller/CrdController.java
  crd-service/src/main/java/com/istizo/crd_service/web/controller/IstioRouteController.java
  crd-service/src/main/java/com/istizo/crd_service/web/dto/CrdRequestDTO.java
  crd-service/src/main/java/com/istizo/crd_service/web/dto/CrdResponseDTO.java
  crd-service/src/main/java/com/istizo/crd_service/web/dto/IstioRouteDTO.java
  crd-service/src/main/resources/application.yml
  crd-service/src/test/java/com/istizo/crd_service/CrdServiceApplicationTests.java
Labels: feature

#14 deployment 버전 조회 API
  cluster-service/src/main/java/org/istizo/clusterservice/api/ClusterController.java
  cluster-service/src/main/java/org/istizo/clusterservice/dto/response/DeploymentVersionListResponse.java
  cluster-service/src/main/java/org/istizo/clusterservice/service/ClusterService.java
Labels: enhancement

#16 Vsxd 72 agent helth check 부분 추가
  crd-service/build.gradle
  crd-service/src/main/java/com/istizo/crd_service/global/config/webConfig/WebMvcConfig.java
  crd-service/src/main/java/com/istizo/crd_service/web/api/CrdApiSpecification.java
  crd-service/src/main/java/com/istizo/crd_service/web/controller/CrdController.java
  crd-service/src/main/java/com/istizo/crd_service/web/controller/IstioRouteController.java
  crd-service/src/main/resources/application.yml
Labels: feature
